--Direccion
-- \i 'C:\\Users\\Jers_\\OneDrive\\Desktop\\Practica\\eliminarModelo.sql'

DROP TABLE RENTA;
DROP TABLE CLIENTE;
DROP TABLE EMPLEADO;
DROP TABLE INVENTARIO;
DROP TABLE TIENDA;
DROP TABLE DIRECCION;
DROP TABLE TRADUCCION;
DROP TABLE DETALLE_CATEGORIA;
DROP TABLE ELENCO;
DROP TABLE PELICULA;
DROP TABLE CIUDAD;
DROP TABLE ACTOR;
DROP TABLE CLASIFICACION;
DROP TABLE IDIOMA;
DROP TABLE CATEGORIA;
DROP TABLE PAIS;



DROP TABLE datos;